// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/relab/hotstuff/modules (interfaces: BlockChain)
//
// Generated by this command:
//
//	mockgen -destination=../internal/mocks/blockchain_mock.go -package=mocks . BlockChain
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	hotstuff "github.com/relab/hotstuff"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockChain is a mock of BlockChain interface.
type MockBlockChain struct {
	ctrl     *gomock.Controller
	recorder *MockBlockChainMockRecorder
	isgomock struct{}
}

// MockBlockChainMockRecorder is the mock recorder for MockBlockChain.
type MockBlockChainMockRecorder struct {
	mock *MockBlockChain
}

// NewMockBlockChain creates a new mock instance.
func NewMockBlockChain(ctrl *gomock.Controller) *MockBlockChain {
	mock := &MockBlockChain{ctrl: ctrl}
	mock.recorder = &MockBlockChainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockChain) EXPECT() *MockBlockChainMockRecorder {
	return m.recorder
}

// Extends mocks base method.
func (m *MockBlockChain) Extends(block, target *hotstuff.Block) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extends", block, target)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Extends indicates an expected call of Extends.
func (mr *MockBlockChainMockRecorder) Extends(block, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extends", reflect.TypeOf((*MockBlockChain)(nil).Extends), block, target)
}

// Get mocks base method.
func (m *MockBlockChain) Get(arg0 hotstuff.Hash) (*hotstuff.Block, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*hotstuff.Block)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBlockChainMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBlockChain)(nil).Get), arg0)
}

// LocalGet mocks base method.
func (m *MockBlockChain) LocalGet(arg0 hotstuff.Hash) (*hotstuff.Block, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalGet", arg0)
	ret0, _ := ret[0].(*hotstuff.Block)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// LocalGet indicates an expected call of LocalGet.
func (mr *MockBlockChainMockRecorder) LocalGet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalGet", reflect.TypeOf((*MockBlockChain)(nil).LocalGet), arg0)
}

// PruneToHeight mocks base method.
func (m *MockBlockChain) PruneToHeight(height hotstuff.View) []*hotstuff.Block {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneToHeight", height)
	ret0, _ := ret[0].([]*hotstuff.Block)
	return ret0
}

// PruneToHeight indicates an expected call of PruneToHeight.
func (mr *MockBlockChainMockRecorder) PruneToHeight(height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneToHeight", reflect.TypeOf((*MockBlockChain)(nil).PruneToHeight), height)
}

// Store mocks base method.
func (m *MockBlockChain) Store(arg0 *hotstuff.Block) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Store", arg0)
}

// Store indicates an expected call of Store.
func (mr *MockBlockChainMockRecorder) Store(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockBlockChain)(nil).Store), arg0)
}
